### ISSUE TITLE
General

### ISSUE THREAD

**Issue by Kevinpaulose05** [Kevinpaulose05/Kevinpaulose05.github.io#2]
Any suggestions or part you may want to work on, feel free to share and discuss with me!

**Comment by johanbove** [comment]
A couple of things I found when I looked at your site (which I also showed you in the PRs): 
- Fix the typos and content:
   - Think about the message first, not the form. Use a spelling corrector. Write the contents of your site in a word processing tool first. ("atleast" is not an English word ;-) )
   - Get facts checked: Anyone can create a "graph" of their "experience": add more examples, perhaps certificates to prove you really have the experience.
- Make your site faster:
   - Do you really need the full Bootstrap CSS library or can you simply write your own layout using CSS (see CSS grid)?
   - Do you really need all the web fonts or can you get rid of unused ones?
- Speed up the initial load of the site:
   - Check external libraries: do you really need these?
   - Use dns-prefetch (https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch)
   - The "triangle swarm" animation is cool, but what benefit does it have for your visitors? Unless you code it yourself and can show the source code?
